<?php 

class Constantes {

    const CODIGO_ESTADO_CURSANDO = '01';
    const CODIGO_ESTADO_REGULARIZO = '02';
    const CODIGO_ESTADO_PROMOCIONO = '03';
    const CODIGO_ESTADO_APROBO = '04';
    const CODIGO_ESTADO_LIBRE = '05';
    const CODIGO_ESTADO_SUSPENSO = '06';

    const CODIGO_CURSADO_PRESENCIAL = 201;
    const CODIGO_CURSADO_SEMIPRESENCIAL = 202;
    const CODIGO_CURSADO_LIBRE = 203;

    const CODIGO_HOMOLOGACION = 1022;

    const CODIGO_PRIMER_TURNO = 1001;
    const CODIGO_SEGUNDO_TURNO = 1002;
    const CODIGO_TERCER_TURNO = 1003;
    const CODIGO_MESA_ESPECIAL_TURNO = 1004;

    const CODIGO_INSCRIPCION_SIN_DEFINIR = 1000;
    const CODIGO_INSCRIPCION_PRIMER_TURNO = 1005;
    const CODIGO_INSCRIPCION_SEGUNDO_TURNO = 1006;
    const CODIGO_INSCRIPCION_TERCER_TURNO = 1007;
    const CODIGO_INSCRIPCION_MESA_ESPECIAL = 1008;
    const CODIGO_INSCRIPCION_INTERMEDIA_PRIMER_TURNO = 1009;
    const CODIGO_INSCRIPCION_INTERMEDIA_SEGUNDO_TURNO = 1010;

    const CODIGO_PRIMER_LLAMADO = 1020;
    const CODIGO_SEGUNDO_LLAMADO = 1021;

    const CODIGO_INSCRIPCION_CURSADO = 1023;

    const CODIGO_FORMATO_MATERIA = 2101;
    const CODIGO_FORMATO_TALLER = 2102;
    const CODIGO_FORMATO_SEMINARIO = 2103;
    const CODIGO_FORMATO_TRABAJO_CAMPO = 2104;
    const CODIGO_FORMATO_TALLER_PRACTICA = 2105;
    const CODIGO_FORMATO_PROYECTO = 2106;
    const CODIGO_FORMATO_MODULO = 2107;
    const CODIGO_FORMATO_LABORATORIO = 2108;

    const CODIGO_CAMPO_FORMACION_GENERAL = 3000;
    const CODIGO_CAMPO_FORMACION_PRACTICA_PROFESIONAL = 3001;
    const CODIGO_CAMPO_FORMACION_ESPECIFICA = 3002;
    const CODIGO_CAMPO_FORMACION_FUNDAMENTO = 3003;
}    
